---
name: Log-Dispatch-Email-EmailSend
version: 0.01
author:
  - 'Dave Rolsky, <autarch@urth.org>'
abstract: Subclass of Log::Dispatch::Email that uses Email::Send
license: perl
requires:
  Email::Send: 0
  Email::Simple::Creator: 0
  Log::Dispatch: 2
  Params::Validate: 0
provides:
  Log::Dispatch::Email::EmailSend:
    file: lib/Log/Dispatch/Email/EmailSend.pm
    version: 0.01
generated_by: Module::Build version 0.2609
